### ISSUE TITLE
Feedback and more... 

### ISSUE THREAD

**Issue by h3ct0rjs** [Aldair47x/FileMetadata-Microservice#1]
Hi @Aldair47x lol,
I just want  to let you know that you're improving your tech skills too fast, and that's pretty cool :rocket: , just a little thing to Improve in all your repos, please add a proper readme.md :smile:  file sometimes we as programmers want to check a cool/brief... description, you know a little motivation to read the code and say 'wow this is awesome :smiling_imp:  If you're  able to create gifs or screencast like [this]( https://asciinema.org/a/Zsez7V9HBmCMuv2dMuOjV46qd) or _gifs(Check Product hunt, the meca of new cool apps and tech)_ it would be very useful for other programmers. 

Just Keep going, and try harder, 
Best Regards, 
Hector F.

**Comment by Aldair47x** [comment]
lmo @h3ct0rjs thanks for your feed back and the motivated words that always are to improve myself in a better way. the readme.md was already updated  :smile:
